services:
  # MySQL Database
  dbase:
    image: mysql:8.0
    container_name: mysql-vollmed-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_local_lab_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - vollmed-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin-nest-lab
    restart: always
    environment:
      PMA_HOST: dbase
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8844:80"
    networks:
      - vollmed-network
    depends_on:
      - dbase

networks:
  vollmed-network:
    driver: bridge

volumes:
  mysql_local_lab_data:
