spring:
  application:
    name: api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vollmed_api?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem

  flyway:
    locations: classpath:db/migrations
    #repair-on-migrate: true
    #clean-disabled: false


  server:
    error:
      include-stacktrace: never


api:
  jwt:
    secret: ${JWT_SECRET:xjhsuu5478t3gb2k}
